### ISSUE TITLE
Russia and other free freedom vpn 

### ISSUE THREAD

**Issue by trimechee** [Snawoot/dumbproxy#15]
Hello @Snawoot thank you for alle thse amzing ans awesome softwares ! 💯 🥇 

i find somme open source russian vpn to avoid censorship, but some ar in russian language so i wasn't able to use them, but others are in english language, so do you think they are reliable option even if these vpn seem to be intended only for russian people please ?

https://censortracker.org/

https://github.com/anticensority/runet-censorship-bypass

https://openrunet.org/index.html

https://github.com/roskomsvoboda

https://github.com/roskomsvoboda/censortracker

https://antizapret.prostovpn.org/

https://roskomsvoboda.org/

and these famous software 

https://ultrasurf.us/

https://dongtaiwang.com/loc/phome_en.php

this is a new p2p browser, i don't know if this browser could replace vpn

https://censorship.no/en/index.html

i find free vpn intended for people who defend human rights in dictatorships, are these vpn are reliable please?

https://survpn.net/

https://calyx.net/

https://www.vpngate.net/en/download.aspx

https://riseup.net/en/vpn ( avoid this vpn because in reddit, some poeple says it requires donations to work)

https://leap.se/

other vpn tricks

https://www.your-freedom.net/index.php?id=home

https://github.com/trailofbits/algo

https://github.com/esptl/OpenVPNUI

https://github.com/NekoX-Dev/NekoX

   Thank you very much !

**Comment by Snawoot** [comment]
Hello! Thanks!

I've never heard about most of solutions from this list.

In terms of availability they are as reliable as possible for free solution -- as long as it doesn't cost too much for service owner and it's not too hard to maintain it. Some services may provide access logs to law enforcement (including russian).

Basically, if you don't care much or you need one-off solution to visit some blocked resource, you can use anything what works for you. Otherwise, if you have high standards or need such solution on daily basis, find some cheap VPS for 2 euro/mo, deploy and self-hosted solution of your choice and be happy.

Hope that answers your question.

**Comment by trimechee** [comment]
Thank you very much for this useful infomtions :) and sorry for the delay, I thought I answered weeks ago.....

other questions please, is there a security risk if we use nth-dump, hola-proxy software? Or just a privacy risk? ie when we surf the internet, can we be infected by viruses and malware by using these vpn?

https://github.com/Snawoot/hola-proxy


I find this review: "Hola is one of the worst free VPNs we've reviewed. It logs all your online activity, shares your information, and doesn't encrypt your connection. It is categorically unsafe and anyone that chooses to download it risks their privacy, personal identity, and online security." ans "Sells free user bandwidth to premium users"

https://www.top10vpn.com/reviews/hola-free-vpn/

What do you think, is it true please?


I don't really care if my identity is hidden or encrypted, I just want to use vpn to bypass censorship and blocking to watch streaming sites, I'm in a country that allows you to watch streaming sites from all over the world lol so I have no problem but some sites can block access to people from certain African countries, so do I risk getting malware viruses if I use nth-dump or even the official nthLink please ?

Thanks a lot !

**Comment by Snawoot** [comment]
@trimechee Hi!

>  is there a security risk if we use nth-dump, hola-proxy software?

I don't recommend to use nthLink and nth-dump at all because its security flaws allow to break encryption. Here is details about it: [EN](https://snawoot.github.io/stripping_nthlink_vpn_encryption/), [RU](https://habr.com/ru/post/684676/).

Hola was known for selling free user bandwith to premium users. Maybe there were also concerns about lack of encryption in some cases, I don't know anything about it. But my implementation of client for their proxies ([hola-proxy](https://github.com/Snawoot/hola-proxy)) has only safe subset of communication implemented and doesn't share user's bandwidth. In that sense, it is as safe as any other "VPN" browser extension, just uses Hola servers. Back then it was also possible to use residential IP addresses through hola-proxy, but later Hola restricted usage to datacenter servers only. This way "hola-proxy" project has lost most of it interesting properties, but still is an option to use some free proxies.

> What do you think, is it true please?

These concerns may be true for their client apps, but not true for my implementation. My implementation just retrieves credentials for HTTPS (HTTP CONNECT over TLS) proxies and uses them with strict TLS encryption. No hidden traffic sharing, no plaintext communications.

> I don't really care if my identity is hidden or encrypted, I just want to use vpn to bypass censorship and blocking to watch streaming sites, I'm in a country that allows you to watch streaming sites from all over the world lol so I have no problem but some sites can block access to people from certain African countries, so do I risk getting malware viruses if I use nth-dump or even the official nthLink please ?

If only changing IP country is your concern and confidentiality/privacy/security is not needed, then you can use whatever works for you to unblock access. At least my implementations add no risk of malware infection. Just don't visit garbage sites and don't download and run fishy stuff, then you'll be fine.

**Comment by trimechee** [comment]
Great awesome ! Very interesting useful important informations ! Thank you very much for these precious informations and big precious help :) 💯 🥇

**Comment by lk-geimfari** [comment]
Hi @trimechee My name is Isaac, I'm from @roskomsvoboda and I'm the developer of Censor Tracker.

We created Censor Tracker not only for Russian users, but also for all users around the world.

We also localized Censor Tracker into English and Ukrainian (if you help us to translate it into your language, we'll be happy to add your language you need too).

We allow users to proxy sites from their own list, not only those blocked in Russia.

Translated with www.DeepL.com/Translator (free version)

**Comment by trimechee** [comment]
@lk-geimfari  Great !! Thank  you very much for your wonderful software which makes our lifes more comfortable and safe ! 💯 🥇
