### ISSUE TITLE
TLS handshake error using "-autocert"

### ISSUE THREAD

**Issue by Flig** [Snawoot/dumbproxy#34]
Trying to use https proxy with autocert gives me error:
`server.go:3228: http: TLS handshake error from 219.67.76.63:54604: acme/autocert: missing server name`
`219.67.76.63` - is my local IP, not the server

**Comment by Snawoot** [comment]
Hi!

Yeah, you need some domain name to issue certificate automatically and connect to server by it's domain name (otherwise handshake won't have domain in SNI)

Here is a complete guide in wiki for reference, should give you an idea by example: https://github.com/Snawoot/dumbproxy/wiki/Quick-deployment

**Comment by Flig** [comment]
just want to inform you that I had the domain name, I got it through freemyip.com.
The  issue was different here, the same name was used by "some" Telegram user and a few minutes after registration, a Telegram server was already "sitting" on my domain name.

**Comment by Snawoot** [comment]
Interesting, not sure how that's possible. Maybe some bug with service or someone else used your token to update address for domain.

**Comment by Flig** [comment]
I apologize for that. freemyip.com generates bind/update link and it was sent in the Telegram chat and the preview-bot followed this link.
