### ISSUE TITLE
Safari (iOS / MacOS) support

### ISSUE THREAD

**Issue by kozhin** [Snawoot/dumbproxy#41]
Hey folks,

I'm curious if Dumbproxy can work with Safari both on iOS and MacOS.

Recently I've tried to add my PAC string into proxy configuration of my WiFi network on iOS and Mac OS Sonoma, but Safari stopped serving any websites (connection error). At the same time everything works just fine with FireFox.

Is this a known issue? Are there any workarounds?

**Comment by Mobeidat** [comment]
Same here, facing such an issue with multiple sites.

@kozhin - what is the website URL you're facing issue with

**Comment by Snawoot** [comment]
Hi!

I guess Safari supports only plaintext HTTP proxies, not proxies working over TLS. But still you can make it work. I can suggest following options:

* Run [steady-tun](https://github.com/Snawoot/steady-tun) on your machine or within your local network. steady-tun can accept plaintext connections and forward them wrapped in TLS to dumbproxy. So you'll connect to port which steady-tun is listening instead of connecting to remote server port directly.
* Use dumbproxy itself on client side. Pretty much the same idea, you can run it like this: `dumbproxy -proxy https://login:password@example.tld`. It will accept HTTP requests on plain HTTP proxy port 8080 and forward them via TLS with authentication.
