### ISSUE TITLE
pass https web requests to web server, serve https proxy requests by self

### ISSUE THREAD

**Issue by xoid** [Snawoot/dumbproxy#46]
1. How autocert works?
2. Can you kindly add the support to multiplex https web requests to real web server to bind dumbproxy on 443 port ?

**Comment by Snawoot** [comment]
1. `-autocert` option is a convenience feature which allows dumbproxy to issue certificates automatically with any ACME-compatible provider (LetsEncrypt, BuyPass, ...). In order to do that, it has to listen port 443 to be able to complete "tls-alpn-01" challenge or port 80 to complete "http-01" challenge. The later one is activated with option like `-autocert-http :80`. Once dumbproxy receives TLS connection, it lookups cert cache for certificate matching domain specified in servername indication in TLS handshake for this connection. If cert is not found or outdated, it tries to issue a new one and caches it. So in [simplest case](https://github.com/Snawoot/dumbproxy?tab=readme-ov-file#example-http-proxy-over-tls-letsencrypt-automatic-certs) certificates and TLS "just work".
2. There is already a plenty of reverse proxy software which can serve connections in front of dumbproxy and forward them to various destinations. I suggest to use [HAProxy](https://www.haproxy.org/) for that purpose. It is possible to switch backends based on servername (domain) in TLS connection request or by value of authorization headers or whatever you can come up with.

I'm not planning to add support for proxying of requests to some other site for following reasons:

* There is already software which does that better and if you're trying to achieve port sharing by multiple applications probably some reverse proxy should manage that instead of dumbproxy being cornerstone.
* In regard to censorship circumvention such strategy is a bit fruitless. It's quite easy to figure out that such masquerade web page doesn't really belong to this server; sometimes other domain references in the page body may suggest that. Instead other defense strategies might work better:
  * dumbproxy can generates HTTP error pages to which provide no clue it's a proxy. [See also](https://github.com/Snawoot/dumbproxy?tab=readme-ov-file#authentication) `hidden_domain` option for password-based auth to enable defense against active probing.
  * It's possible to enable mTLS-based authentication and disallow connections without client certificate. In that case you'll have to use mTLS-capable software on the client side like [steady-tun](https://github.com/Snawoot/steady-tun), but active probes will be completely eliminated because prober won't be able to establish TLS session to begin with.
